### ISSUE TITLE
PnP PowerShell version 2.2.2 support?

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/predictors#1]
Hi @anoopt, is pnp powershell 2.2.2 supported already? I'm getting 'unable to load predictions from GitHub' since installing this version of pnp.powershell. 

Updating the predictor module does not seem to help.

**Comment by anoopt** [comment]
Hi @martinlingstuyl . Thank you for letting me know about this. It needs a minor update in the build script of PnP PowerShell. I have asked Gautam to update that. I will let you know once that is done.

**Comment by anoopt** [comment]
Hi @martinlingstuyl . This should be fine now.

I checked with latest version of PnP PowerShell (2.2.0) and I am not seeing the message.

Can you please confirm?

**Comment by martinlingstuyl** [comment]
Will do so after holidays, thanks!

**Comment by martinlingstuyl** [comment]
Hi @anoopt, I can verify the error is gone 👏
